#This is intended for docker-development environment
version: '3.2'

services:  
  #Backend   
  yii2-minimal:
    build: ./
    container_name: yii-minimal
    ports:
      - 40811:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    networks:
        - yii2min-network
networks:
    yii2min-network:
        driver: bridge

